name: places

description: The app which helps people to find awesome places.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 0.19.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/
    - res/icons/

    - fonts:
      - family: Roboto
        fonts:
          - asset: res/fonts/Roboto-Regular.ttf
          - asset: res/fonts/Roboto-Medium.ttf
            weight: 500
          - asset: res/fonts/Roboto-Bold.ttf
            weight: 700


