/*
* Assets urls
*/
const String base = 'res',
      icons = 'icons';

const String favoriteIconURL = '$base/$icons/heart.svg',
      listDarkIconURL = '$base/$icons/list_dark.svg',
      mapDarkIconURL = '$base/$icons/map_dark.svg',
      settingsDarkIconURL = '$base/$icons/settings_dark.svg',
      favoriteDarkIconURL = '$base/$icons/heart_dark.svg',
      emptyVisitingWantURL = '$base/$icons/empty_visiting_want.svg',
      emptyVisitingURL = '$base/$icons/empty_visiting.svg',
      calendarIconURL = '$base/$icons/calendar.svg',
      removeIconURL = '$base/$icons/remove.svg',
      shareIconURL = '$base/$icons/share.svg',
      searchIconURL = '$base/$icons/search.svg',
      filterIconURL = '$base/$icons/filter.svg',
      cafeIconURL = '$base/$icons/cafe.svg',
      hotelIconURL = '$base/$icons/hotel.svg',
      museumIconURL = '$base/$icons/museum.svg',
      parkIconURL = '$base/$icons/park.svg',
      restaurantIconURL = '$base/$icons/restaurant.svg',
      churchIconURL = '$base/$icons/church.svg',
      mountainsIconURL = '$base/$icons/mountains.svg',
      lakeIconURL = '$base/$icons/lake.svg',
      wonderIconURL = '$base/$icons/wonder.svg',
      sportIconURL = '$base/$icons/sport.svg',
      infoIconURL = '$base/$icons/info.svg',
      plusIconURL = '$base/$icons/plus.svg',
      subtractIconURL = '$base/$icons/subtract.svg',
      trashIconURL = '$base/$icons/trash.svg',
      routerIconURL = '$base/$icons/router.svg',
      bagIconURL = '$base/$icons/bag.svg',
      touchIconURL = '$base/$icons/touch.svg',
      logoIconURL = '$base/$icons/logo.svg',
      photocameraIconURL = '$base/$icons/photocamera.svg',
      imageIconURL = '$base/$icons/image.svg',
      copyIconURL = '$base/$icons/copy.svg';

